### ISSUE TITLE
Engineering Fundamentals Metrics

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#43]
Feature #29 

### Description

As part of our success criteria for the engagement we want to contribute to the establishment and adoption of engineering best practices by the EDC community. To measure improvements, we need to collect metrics for the key areas of interest and visualize how these metrics change over time.

### Acceptance Criteria

- [x] Metrics to be collected and reported on are defined
- [x] A first report on initial metrics is available
- [ ] Follow-up stories to add additional metrics (which might depend on other stories and might not be available yet) are created.

Metrics in target for collection include the following (at this time):

- [x] Code Coverage
- [x] PR Age
- [x] Frequency of PRs
- [ ] Count of Rejected PRs
- [x] Cyclomatic Complexity
- [ ] Linting Errors
- [x] Total # of ADRs

> Note that in order to complete this story, the dependent items need to be completed:
> 
> agera-edc/DataSpaceConnector#42 
> agera-edc/DataSpaceConnector#56 
> agera-edc/DataSpaceConnector#34

**Comment by chrislomonico** [comment]
Current state of the power bi report has been checked into our internal Azure-DevOps [PR](https://dev.azure.com/CSECodeHub/492280%20-%20Eclipse%20Dataspace%20Platform%20(EDC)/_git/internal-artifacts/pullrequest/1917)

Note that at this stage, CodeCov access is only available (for my account) in our internal Repo.  This is not an issue at this time as the CodeCov reports should be generated for the main EDC repo as well.  

I have requested access to the EDC repo from my CodeCov account.

A few points to mention:

- We do have metrics for the following in CodeCov reports:
-- Code Coverage
-- Cyclomatic Complexity
- Instead of imbedding these metrics in the PBI report; a dashboard should be made that displays the PBI report sections and has the CodeCov reports present (note that it is not possible to include the codecov specific graphs/tables in the PBI in a meaningful way).
- Follow up stories for the Linting and new Dashboard will need to be created
- Rejected PR's may not be possible given the information that is provided from the API; it is my belief that with the PR insights we have in the report, we have enough meaningful information.

**Comment by arckumari** [comment]
All data we wanted is accumulated. closing this out and next one will be created for follow up work.
